### ISSUE TITLE
Add possibility to have custom headers

### ISSUE THREAD

**Issue by tbille** [canonical-web-and-design/canonicalwebteam.http#12]
In snapcraft we add a header: `"storefront ({commit_hash};{environment})"` we making requests. This is  helpul for the teams that handle the APIs

To be able to use this project in snapcraft.io it would be great to have the possibility to add custom headers on inititalisation of the project or the [Cached]Session class.

**Comment by jpmartinspt** [comment]
@tbille @nottrobin from what I can tell this is already supported. 

https://github.com/canonical-web-and-design/canonicalwebteam.http/blob/ea9eff0ce0920feabf03a246bb9f695284921e10/canonicalwebteam/http/__init__.py#L68

https://github.com/psf/requests/blob/a4c18cd733f97b5659a29589432d8a39e7a0de87/requests/sessions.py#L458

**Comment by jpmartinspt** [comment]
Tested and it works both with `UncachedSession` and `CachedSession` by passing an `headers` dict to the constructor.
